const result = document.getElementById("result");
const output = document.getElementById("output");
const display = document.getElementById("display");
let scripture = ["In the beginning God created the heaven and earth.", "Jesus wept.",
    "Arise, shine for the light is come, and the glory of the Lord is risen upon thee.",
    "And it shall come to pass afterward, that i will pour out my spirit upon all flesh; and your sons and daughter shall prophesy, your old men shall dream dreams, your young men shall see visions.",
    "Come unto me, all ye that have labour and are of heavy laden i will give you rest.",
    "In the beginning was the Word, and the Word was with God, and the Word was God.",
    "Study to show yourself approve unto God, a work man needed not be ashamed rightly divided the word of truth.",
    "Go ye therefore, and teach all nations, baptizing them in the name of the Father, and of the Son, and of the Holy Ghost",
    "Ye have sown much, and bring in little; ye eat, but ye have not enough; ye drink, but ye are not filled with drink; ye clothe you, but there is none warm; and he that earneth wages earneth wages to put it into a bag with holes.",
    "Now faith is the substance of things hoped for, the evidence of things not seen.",
    "I can do all things through Christ which strengtheneth me.",
    "Charity suffereth long, and is kind; charity envieth not; charity vaunteth not itself, is not puffed up.",
    "Now the God of hope fill you with all joy and peace in believing, that ye may abound in hope, through the power of the Holy Ghost.",
    "Trust in the LORD with all thine heart; and lean not unto thine own understanding. In all thy ways acknowledge him, and he shall direct thy paths.",
    "Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you. Let not your heart be troubled, neither let it be afraid.",
    "Have not I commanded thee? Be strong and of a good courage; be not afraid, neither be thou dismayed: for the LORD thy God is with thee whithersoever thou goest.",
    "And be ye kind one to another, tenderhearted, forgiving one another, even as God for Christ's sake hath forgiven you.",
    "But let patience have her perfect work, that ye may be perfect and entire, wanting nothing.",
    "The joy of the LORD is your strength.",
    "If ye have faith as a grain of mustard seed, ye shall say unto this mountain, Remove hence to yonder place, and it shall remove; and nothing shall be impossible unto you.",
    "But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint.",
    "He that loveth not knoweth not God; for God is love.",
    "For I know the thoughts that I think toward you, saith the LORD, thoughts of peace, and not of evil, to give you an expected end.",
    "I will instruct thee and teach thee in the way which thou shalt go: I will guide thee with mine eye.",
    "And let the peace of God rule in your hearts, to the which also ye are called in one body; and be ye thankful.",
    "For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.",
    "For if ye forgive men their trespasses, your heavenly Father will also forgive you.",
    "Rejoicing in hope; patient in tribulation; continuing instant in prayer;",
    "Thou wilt shew me the path of life: in thy presence is fulness of joy; at thy right hand there are pleasures for evermore.",
    "So then faith cometh by hearing, and hearing by the word of God.",
    "God is our refuge and strength, a very present help in trouble.",
    "This is my commandment, That ye love one another, as I have loved you.",
    "And now, Lord, what wait I for? my hope is in thee.",
    "Thy word is a lamp unto my feet, and a light unto my path.",
    "Thou wilt keep him in perfect peace, whose mind is stayed on thee: because he trusteth in thee.",
    "Be strong and of a good courage, fear not, nor be afraid of them: for the LORD thy God, he it is that doth go with thee; he will not fail thee, nor forsake thee.",
    "Judge not, and ye shall not be judged: condemn not, and ye shall not be condemned: forgive, and ye shall be forgiven:",
    "Better is the end of a thing than the beginning thereof: and the patient in spirit is better than the proud in spirit.",
    "Rejoicing in hope; patient in tribulation; continuing instant in prayer;",
    "For we walk by faith, not by sight:",
    "The LORD is my strength and my shield; my heart trusted in him, and I am helped: therefore my heart greatly rejoiceth; and with my song will I praise him.",
    "Love worketh no ill to his neighbour: therefore love is the fulfilling of the law.",
    "Behold, the eye of the LORD is upon them that fear him, upon them that hope in his mercy;",
    "The LORD shall guide thee continually, and satisfy thy soul in drought, and make fat thy bones: and thou shalt be like a watered garden, and like a spring of water, whose waters fail not.",
    "These things I have spoken unto you, that in me ye might have peace. In the world ye shall have tribulation: but be of good cheer; I have overcome the world.",
    "Be strong, and of good courage, and do it: fear not, nor be dismayed: for the LORD God, even my God, will be with thee; he will not fail thee, nor forsake thee, until thou hast finished all the work for the service of the house of the LORD.",
    "As far as the east is from the west, so far hath he removed our transgressions from us.",
    "And let us not be weary in well doing: for in due season we shall reap, if we faint not.",
    "This is the day which the LORD hath made; we will rejoice and be glad in it.",
    "But let him ask in faith, nothing wavering. For he that wavereth is like a wave of the sea driven with the wind and tossed.",
    "Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee; yea, I will help thee; yea, I will uphold thee with the right hand of my righteousness.",
    "And we have known and believed the love that God hath to us. God is love; and he that dwelleth in love dwelleth in God, and God in him.",
    "Be of good courage, and he shall strengthen your heart, all ye that hope in the LORD.",
    "A man's heart deviseth his way: but the LORD directeth his steps.",
    "And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus.",
    "The LORD is my light and my salvation; whom shall I fear? the LORD is the strength of my life; of whom shall I be afraid?",
    "Who is a God like unto thee, that pardoneth iniquity, and passeth by the transgression of the remnant of his heritage? he retaineth not his anger for ever, because he delighteth in mercy.",
    "The LORD is good unto them that wait for him, to the soul that seeketh him. It is good that a man should both hope and quietly wait for the salvation of the LORD.",
    "In the multitude of my thoughts within me thy comforts delight my soul.",
    "For therein is the righteousness of God revealed from faith to faith: as it is written, The just shall live by faith.",
    "The joy of the LORD is your strength.", 
    "And above all things have fervent charity among yourselves: for charity shall cover the multitude of sins.",
    "For whatsoever things were written aforetime were written for our learning, that we through patience and comfort of the scriptures might have hope.",
    "The steps of a good man are ordered by the LORD: and he delighteth in his way.",
    "For the mountains shall depart, and the hills be removed; but my kindness shall not depart from thee, neither shall the covenant of my peace be removed, saith the LORD that hath mercy on thee.",
    "Be of good courage, and he shall strengthen your heart, all ye that hope in the LORD.",
    "Forbearing one another, and forgiving one another, if any man have a quarrel against any: even as Christ forgave you, so also do ye.",
    "Be patient therefore, brethren, unto the coming of the Lord. Behold, the husbandman waiteth for the precious fruit of the earth, and hath long patience for it, until he receive the early and latter rain.",
    "Thou wilt shew me the path of life: in thy presence is fulness of joy; at thy right hand there are pleasures for evermore.",
    "And Jesus answering saith unto them, Have faith in God.",
    "Be ye strong therefore, and let not your hands be weak: for your work shall be rewarded.",
    "A new commandment I give unto you, That ye love one another; as I have loved you, that ye also love one another.",
    "For thou art my hope, O Lord GOD: thou art my trust from my youth.",
    "And thine ears shall hear a word behind thee, saying, This is the way, walk ye in it, when ye turn to the right hand, and when ye turn to the left.",
    "Therefore being justified by faith, we have peace with God through our Lord Jesus Christ:",
    "Watch ye, stand fast in the faith, quit you like men, be strong.",
    "Take heed to yourselves: If thy brother trespass against thee, rebuke him; and if he repent, forgive him. And if he trespass against thee seven times in a day, and seven times in a day turn again to thee, saying, I repent; thou shalt forgive him.",
    "For his anger endureth but a moment; in his favour is life: weeping may endure for a night, but joy cometh in the morning.",
    "Looking unto Jesus the author and finisher of our faith; who for the joy that was set before him endured the cross, despising the shame, and is set down at the right hand of the throne of God.",
    "It is God that girdeth me with strength, and maketh my way perfect.",
    "My little children, let us not love in word, neither in tongue; but in deed and in truth.",
    "The LORD is my portion, saith my soul; therefore will I hope in him.",
    "Shew me thy ways, O LORD; teach me thy paths. Lead me in thy truth, and teach me: for thou art the God of my salvation; on thee do I wait all the day.",
    "Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you. Let not your heart be troubled, neither let it be afraid.",
    "And the LORD, he it is that doth go before thee; he will be with thee, he will not fail thee, neither forsake thee: fear not, neither be dismayed.",
    "Then came Peter to him, and said, Lord, how oft shall my brother sin against me, and I forgive him? till seven times? Jesus saith unto him, I say not unto thee, Until seven times: but, Until seventy times seven.",
    "Better is the end of a thing than the beginning thereof: and the patient in spirit is better than the proud in spirit.",
    "That your faith should not stand in the wisdom of men, but in the power of God.",
    "The LORD is my strength and song, and he is become my salvation: he is my God, and I will prepare him an habitation; my father's God, and I will exalt him.",
    "We love him, because he first loved us.",
    "And hope maketh not ashamed; because the love of God is shed abroad in our hearts by the Holy Ghost which is given unto us.",
    "Thus saith the LORD, thy Redeemer, the Holy One of Israel; I am the LORD thy God which teacheth thee to profit, which leadeth thee by the way that thou shouldest go.",
    "The LORD will give strength unto his people; the LORD will bless his people with peace.",
    "God is my strength and power: and he maketh my way perfect.",
    "For thou, Lord, art good, and ready to forgive; and plenteous in mercy unto all them that call upon thee.",
    "Rest in the LORD, and wait patiently for him: fret not thyself because of him who prospereth in his way, because of the man who bringeth wicked devices to pass.",
    "I will greatly rejoice in the LORD, my soul shall be joyful in my God; for he hath clothed me with the garments of salvation, he hath covered me with the robe of righteousness, as a bridegroom decketh himself with ornaments, and as a bride adorneth herself with her jewels.",
    "I am crucified with Christ: nevertheless I live; yet not I, but Christ liveth in me: and the life which I now live in the flesh I live by the faith of the Son of God, who loved me, and gave himself for me.",
    "Be not ye afraid of them: remember the Lord, which is great and terrible, and fight for your brethren, your sons, and your daughters, your wives, and your houses.",
    "Be kindly affectioned one to another with brotherly love; in honour preferring one another;",
    "I wait for the LORD, my soul doth wait, and in his word do I hope.",
    "Where no counsel is, the people fall: but in the multitude of counsellors there is safety.",
    "And the work of righteousness shall be peace; and the effect of righteousness quietness and assurance for ever.",
    "Be strong, and of good courage, and do it: fear not, nor be dismayed: for the LORD God, even my God, will be with thee.",
    "He will turn again, he will have compassion upon us; he will subdue our iniquities; and thou wilt cast all their sins into the depths of the sea.",
    "For God so loved the world that he gave his only beggoten Son, whosoever believeth in Him shall not perish but have everlasting life.",
    "The statutes of the LORD are right, rejoicing the heart: the commandment of the LORD is pure, enlightening the eyes.",
    "And all things, whatsoever ye shall ask in prayer, believing, ye shall receive.",
    "Behold, God is my salvation; I will trust, and not be afraid: for the LORD JEHOVAH is my strength and my song; he also is become my salvation.",
    "And walk in love, as Christ also hath loved us, and hath given himself for us an offering and a sacrifice to God for a sweet-smelling savour.",
    "Why art thou cast down, O my soul? and why art thou disquieted within me? hope thou in God: for I shall yet praise him for the help of his countenance.",
    "For this God is our God for ever and ever: he will be our guide even unto death.",
    "These things I have spoken unto you, that in me ye might have peace. In the world ye shall have tribulation: but be of good cheer; I have overcome the world.",
    "Follow peace with all men and holiness without which no man can see God.",
    "As far as the east is from the west, so far hath he removed our transgressions from us.",
    "Be ye also patient; stablish your hearts: for the coming of the Lord draweth nigh.",
    "This is the day which the LORD hath made; we will rejoice and be glad in it.",
    "I have fought a good fight, I have finished my course, I have kept the faith:",
    "Yea, though I walk through the valley of the shadow of death, I will fear no evil: for thou art with me; thy rod and thy staff they comfort me.",
    "And above all these things put on charity, which is the bond of perfectness.",
    "Ask and it shall be given you, seek, and ye shall found, knock and it shall open unto you",
    "And it shall come to pass afterward, that i will pour out my spirit upon all flesh; and your sons and your daughters shall prophesy, your old men shall dream dreams, your young men shall see vision:",
    "Thou wilt keep him in perfect peace, whose mind is stayed on thee: because he trusteth in thee.",
    "Be strong and of a good courage: for unto this people shalt thou divide for an inheritance the land, which I sware unto their fathers to give them.",
    "Then came Peter to him, and said, Lord, how oft shall my brother sin against me, and I forgive him? Jesus saith unto him, I say not unto thee, Until seven times: but, Until seventy times seven.",
    "But if we hope for that we see not, then do we with patience wait for it.",
    "Thou wilt shew me the path of life: in thy presence is fulness of joy; at thy right hand there are pleasures for evermore.",
    "Whom having not seen, ye love; in whom, though now ye see him not, yet believing, ye rejoice with joy unspeakable and full of glory: Receiving the end of your faith, even the salvation of your souls.",
    "Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee; yea, I will help thee; yea, I will uphold thee with the right hand of my righteousness.",
    "By this shall all men know that ye are my disciples, if ye have love one to another.",
    "But I will hope continually, and will yet praise thee more and more.",
    "I will instruct thee and teach thee in the way which thou shalt go: I will guide thee with mine eye.",
    "Therefore being justified by faith, we have peace with God through our Lord Jesus Christ:",
    "Be strong, and of good courage, and do it: fear not, nor be dismayed: for the LORD God, even my God, will be with thee.",
    "And be ye kind one to another, tenderhearted, forgiving one another, even as God for Christ's sake hath forgiven you.",
    "Wait on the LORD, and keep his way, and he shall exalt thee to inherit the land: when the wicked are cut off, thou shalt see it.",
    "Then was our mouth filled with laughter, and our tongue with singing: then said they among the heathen, The LORD hath done great things for them.",
    "So then faith cometh by hearing, and hearing by the word of God.",
    "God is our refuge and strength, a very present help in trouble.",
    "Hereby perceive we the love of God, because he laid down his life for us: and we ought to lay down our lives for the brethren.",
    "This I recall to my mind, therefore have I hope. It is of the LORD'S mercies that we are not consumed, because his compassions fail not. They are new every morning: great is thy faithfulness.",
    "He restoreth my soul: he leadeth me in the paths of righteousness for his name's sake." ,
    "For unto us a child is born, unto us a son is given: and the government shall be upon his shoulder: and his name shall be called Wonderful, Counsellor, The mighty God, The everlasting Father, The Prince of Peace.",
    "The LORD is my light and my salvation; whom shall I fear? the LORD is the strength of my life; of whom shall I be afraid?",
    "Blessed is he whose transgression is forgiven, whose sin is covered. Blessed is the man unto whom the LORD imputeth not iniquity, and in whose spirit there is no guile.",
    "Behold, we count them happy which endure. Ye have heard of the patience of Job, and have seen the end of the Lord; that the Lord is very pitiful, and of tender mercy.",
    "The LORD is my strength and my shield; my heart trusted in him, and I am helped: therefore my heart greatly rejoiceth; and with my song will I praise him.",
    "But without faith it is impossible to please him: for he that cometh to God must believe that he is, and that he is a rewarder of them that diligently seek him.",
    "He giveth power to the faint; and to them that have no might he increaseth strength.",
    "But God commendeth his love toward us, in that, while we were yet sinners, Christ died for us.",
    "For thou art my hope, O Lord GOD: thou art my trust from my youth.",
    "Guide your heart with all digilence, for out of it are the issues of life.",
    "Let not your heart be troubled: ye believe in God, believe also in me.",
    "Can two walk together, expect they be agreed?",
    "Come now, and let us reason together, saith the LORD: though your sins be as scarlet, they shall be as white as snow; though they be red like crimson, they shall be as wool.",
    "For to be carnally minded is death; but to be spiritually minded is life and peace.",
    "For our heart shall rejoice in him, because we have trusted in his holy name.",
    "And be not conformed to this world: but be ye transformed by the renewing of your mind, that ye may prove what is that good, and acceptable, and perfect, will of God.",
    "It is God that girdeth me with strength, and maketh my way perfect.",
    "And above all things have fervent charity among yourselves: for charity shall cover the multitude of sins.",
    "Now the God of hope fill you with all joy and peace in believing, that ye may abound in hope, through the power of the Holy Ghost.",
    "Train up a child in the way he should go: And when he is old, he will not depart from it.",
    "And let the peace of God rule in your hearts, to the which also ye are called in one body; and be ye thankful.",
    "Have not I commanded thee? Be strong and of a good courage; be not afraid, neither be thou dismayed: for the LORD thy God is with thee whithersoever thou goest.",
    "Judge not, and ye shall not be judged: condemn not, and ye shall not be condemned: forgive, and ye shall be forgiven:",
    "Better is the end of a thing than the beginning thereof: and the patient in spirit is better than the proud in spirit.",
    "For his anger endureth but a moment; in his favour is life: weeping may endure for a night, but joy cometh in the morning.",
    "The theif cometh not only but to steal, to kill, and to destroy.",
    "The LORD is my strength and my shield; my heart trusted in him, and I am helped: therefore my heart greatly rejoiceth; and with my song will I praise him.",
    "This is my commandment, That ye love one another, as I have loved you.",
    "And now, Lord, what wait I for? my hope is in thee.",
    "I will instruct thee and teach thee in the way which thou shalt go: I will guide thee with mine eye.",
    "Man that is born of a woman is of few days, and full of troubles.",
    "Children obey your parent in the Lord, for this is right.",
    "And be ye kind one to another, tenderhearted, forgiving one another, even as God for Christ's sake hath forgiven you.",
    "And let us not be weary in well doing: for in due season we shall reap, if we faint not.",
    "This is the day which the LORD hath made; we will rejoice and be glad in it.",
    "But let him ask in faith, nothing wavering. For he that wavereth is like a wave of the sea driven with the wind and tossed.",
    "From henceforth, let no man trouble me, for i bear in my body the mark of our Lord Jesus Christ.",
    "And we have known and believed the love that God hath to us. God is love; and he that dwelleth in love dwelleth in God, and God in him.",
    "Be of good courage, and he shall strengthen your heart, all ye that hope in the LORD.",
    "it is not of him that willest, nor of him that runneth, but of God that showeth mercy.",
    "O give thanks unto the LOrd for is He good and His mercies endureth for ever.",
    "The LORD is my light and my salvation; whom shall I fear? the LORD is the strength of my life; of whom shall I be afraid?",
    "Who is a God like unto thee, that pardoneth iniquity, and passeth by the transgression of the remnant of his heritage? he retaineth not his anger for ever, because he delighteth in mercy.",
    "The LORD is good unto them that wait for him, to the soul that seeketh him. It is good that a man should both hope and quietly wait for the salvation of the LORD.",
    "In the multitude of my thoughts within me thy comforts delight my soul.",
    "And Jesus answering saith unto them, Have faith in God.",
    "Rejoice not against me, O mine enemy: when I fall, I shall arise; when I sit in darkness, the LORD shall be a light unto me.",
    "Go ye therefore, and teach all nations, baptizing them in the name of the Father, and of the Son, and of the Holy Ghost.",
    "I wait for the LORD, my soul doth wait, and in his word do I hope.",
    "And thine ears shall hear a word behind thee, saying, This is the way, walk ye in it.",
    "For whatsoever is born of God overcometh the world: and this is the victory that overcometh the world, even our faith.",
    "But as it is written, Eye hath not seen, nor ear heard, Neither have entered into the heart of man, The things which God hath prepared for them that love him.",
    "As far as the east is from the west, so far hath he removed our transgressions from us.",
    "For ye have need of patience, that, after ye have done the will of God, ye might receive the promise.",
    "For the kingdom of God is not meat and drink; but righteousness, and peace, and joy in the Holy Ghost.",
    "The things which are impossible with men are possible with God.",
    "Blessed is the man whose strength is in thee; in whose heart are the ways of them.",
    "And walk in love, as Christ also hath loved us, and hath given himself for us.",
    "Which hope we have as an anchor of the soul, both sure and stedfast.",
    "Let this mind be in you, which was also in Christ Jesus.",
    "LORD, thou wilt ordain peace for us: for thou also hast wrought all our works in us.",
    "Watch ye, stand fast in the faith, quit you like men, be strong.",
    "To the Lord our God belong mercies and forgivenesses, though we have rebelled against him.",
    "I waited patiently for the LORD; and he inclined unto me, and heard my cry.",
    "Your heart shall rejoice, and your joy no man taketh from you.",
    "What time I am afraid, I will trust in thee.",
    "The LORD JEHOVAH is my strength and my song; he also is become my salvation.",
    "And the Lord direct your hearts into the love of God.",
    "Happy is he that hath the God of Jacob for his help, whose hope is in the LORD his God.",
    "But he knoweth the way that I take: when he hath tried me, I shall come forth as gold.",
    "Now the Lord of peace himself give you peace always by all means.",
    "He shall not be afraid of evil tidings: his heart is fixed, trusting in the LORD.",
    "I, even I, am he that blotteth out thy transgressions for mine own sake.",
    "Wait on the LORD: be of good courage, and he shall strengthen thine heart.",
    "In thy presence is fulness of joy; at thy right hand there are pleasures for evermore.",
    "This is the work of God, that ye believe on him whom he hath sent.",
    "In the day when I cried thou answeredst me, and strengthenedst me with strength in my soul.",
    "We love him, because he first loved us.",
    "My soul, wait thou only upon God; for my expectation is from him.",
    "And the LORD shall guide thee continually.",
    "He will speak peace unto his people.",
    "Be not afraid, but speak, and hold not thy peace.",
    "For thou, Lord, art good, and ready to forgive; and plenteous in mercy.",
    "Blessed the Lord o my soul, and forget not all his benefits.",
    "Then will I go unto the altar of God, unto God my exceeding joy.",
    "The just shall live by his faith.",
    "The LORD will give strength unto his people.",
    "By this shall all men know that ye are my disciples, if ye have love one to another.",
    "Thou art my hiding place and my shield: I hope in thy word.",
    "Man's goings are of the LORD; how can a man then understand his own way?",
    "And the work of righteousness shall be peace.",
    "In God have I put my trust: I will not be afraid.",
    "But there is forgiveness with thee, that thou mayest be feared.",
    "But let patience have her perfect work.",
    "The joy of Jerusalem was heard even afar off.",
    "And the light shineth in darkness, and the darkness comprehend it not.",
    "Honour thy father and thy mother, which is the first with promise.",
    "Love worketh no ill to his neighbour: therefore love is the fulfilling of the law.",
    "Behold, the eye of the LORD is upon them that fear him, upon them that hope in his mercy.",
    "I will lead them in paths that they have not known.",
    "And I will give peace in the land, and ye shall lie down, and none shall make you afraid.",
    "The LORD is on my side; I will not fear: what can man do unto me?",
    "Look upon mine affliction and my pain; and forgive all my sins.",
    "Truly my soul waiteth upon God: from him cometh my salvation.",
    "Let all those that put their trust in thee rejoice.",
    "If thou wouldest believe, thou shouldest see the glory of God?",
    "Put on thy strength, O Zion.",
    "And now abideth faith, hope, charity, these three; but the greatest of these is charity.",
    "Remember the word unto thy servant, upon which thou hast caused me to hope.",
    "Teach me to do thy will; for thou art my God: thy spirit is good; lead me into the land of uprightness.",
    "Peace, peace to him that is far off, and to him that is near, saith the LORD.",
    "Thou shalt not be afraid for the terror by night.",
    "If my people, which are called by my name, shall humble themselves, and pray... then will I hear from heaven, and will forgive their sin.",
    "Rest in the LORD, and wait patiently for him.",
    "I will greatly rejoice in the LORD, my soul shall be joyful in my God.",
    "Let us hold fast the profession of our faith without wavering.",
    "God is in the midst of her; she shall not be moved.",
    "If a man love me, he will keep my words.",
    "But I will hope continually, and will yet praise thee more and more.",
    "Thou in thy mercy hast led forth the people which thou hast redeemed.",
    "Great peace have they which love thy law: and nothing shall offend them.",
    "Yea, though I walk through the valley of the shadow of death, I will fear no evil.",
    "I have blotted out, as a thick cloud, thy transgressions.",
    "So our eyes wait upon the LORD our God.",
    "The LORD hath done great things for us; whereof we are glad.",
    "For with God nothing shall be impossible.",
    "God is the strength of my heart, and my portion for ever.",
    "Beloved, let us love one another: for love is of God.",
    "The LORD taketh pleasure in them that fear him, in those that hope in his mercy.",
    "The meek will he guide in judgment.",
    "Then had thy peace been as a river.",
    "Though I walk in the midst of trouble, thou wilt revive me.",
    "Have mercy upon me, O God, according to thy lovingkindness.",
    "He that is slow to wrath is of great understanding.",
    "O come, let us sing unto the LORD: let us make a joyful noise.",
    "If ye believe not that I am he, ye shall die in your sins.",
    "Be thou their arm every morning, our salvation also in the time of trouble.",
    "That Christ may dwell in your hearts by faith; that ye, being rooted and grounded in love.",
    "My soul fainteth for thy salvation: but I hope in thy word.",
    "The steps of a good man are ordered by the LORD.",
    "Acquaint now thyself with him, and be at peace.",
    "Though an host should encamp against me, my heart shall not fear.",
    "Let the wicked forsake his way... and he will abundantly pardon.",
    "The eyes of all wait upon thee.",
    "Thou hast made him exceeding glad with thy countenance.",
    "And they that know thy name will put their trust in thee.",
    "Be strong, fear not: behold, your God will come with vengeance.",
    "Hatred stirreth up strifes: but love covereth all sins.",
    "Hope thou in God: for I shall yet praise him.",
    "I will bless the LORD, who hath given me counsel.",
    "The LORD lift up his countenance upon thee, and give thee peace.",
    "His heart is established, he shall not be afraid.",
    "I will cleanse them from all their iniquity, whereby they have sinned against me.",
    "Surely I have behaved and quieted myself, as a child that is weaned.",
    "Make a joyful noise unto God, all ye lands.",
    "Thy faith hath made thee whole.",
    "Thou hast a mighty arm: strong is thy hand.",
    "Many waters cannot quench love.",
    "Uphold me according unto thy word, that I may live.",
    "Thou shalt guide me with thy counsel.",
    "My kindness shall not depart from thee, saith the LORD.",
    "He will subdue our iniquities; and thou wilt cast all their sins into the depths of the sea.",
    "When I shall receive the congregation I will judge uprightly.",
    "Be glad in the LORD, and rejoice, ye righteous.",
    "Blessed are they that have not seen, and yet have believed.",
    "For thou hast girded me with strength unto the battle.",
    "Be kindly affectioned one to another with brotherly love.",
    "LORD, I have hoped for thy salvation.",
    "I will go before thee, and make the crooked places straight.",
    "I will both lay me down in peace, and sleep.",
    "Therefore will not we fear, though the earth be removed.",
    "For I will forgive their iniquity, and I will remember their sin no more.",
    "Those that be planted in the house of the LORD shall flourish.",
    "Light is sown for the righteous, and gladness for the upright in heart.",
    "If ye had faith as a grain of mustard seed.",
    "Lead me to the rock that is higher than I.",
    "For whom the LORD loveth he correcteth.",
    "Thy faithfulness is unto all generations.",
    "Order my steps in thy word.",
    "Thou wilt keep him in perfect peace, whose mind is stayed on thee.",
    "I will say of the LORD, He is my refuge and my fortress.",
    "We do not present our supplications before thee for our righteousnesses.",
    "My soul waiteth for the Lord more than they that watch for the morning.",
    "For the LORD taketh pleasure in his people.",
    "Why are ye fearful, O ye of little faith?",
    "The LORD is their strength.",
    "Let us not love in word, neither in tongue; but in deed and in truth.",
    "Trust in him at all times; ye people.",
    "Behold, I have graven thee upon the palms of my hands.",
    "Seek peace, and pursue it.",
    "For he shall give his angels charge over thee.",
    "Thou hast in love to my soul delivered it from the pit of corruption." ,
    "Wait on the LORD, and keep his way.",
    "Make a joyful noise unto the LORD, all the earth.",
    "Let us therefore come boldly unto the throne of grace, that we may obtain mercy, and find grace to help in time of need.",
    "Be still, and know that I am God.",
    "But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you.",
    "But the God of all grace, who hath called us unto his eternal glory by Christ Jesus, after that ye have suffered a while, make you perfect, stablish, strengthen, settle you.",
    "Commit thy way unto the LORD; trust also in him; and he shall bring it to pass.",
    "Owe no man any thing, but to love one another: for he that loveth another hath fulfilled the law.",
    "And the four beasts had each of them six wings about him; and they were full of eyes within: and they rest not day and night, saying, Holy, holy, holy, Lord God Almighty, which was, and is, and is to come.",
    "As far as the east is from the west, so far hath he removed our transgressions from us.",
    "But if we hope for that we see not, then do we with patience wait for it.",
    "But be ye doers of the word, and not hearers only, deceiving your own selves.",
    "If ye have faith, and doubt not, ye shall not only do this which is done to the fig tree, but also if ye shall say unto this mountain, Be thou removed.",
    "This know also, that in the last days perilous times shall come.",
    "Charity suffereth long, and is kind; charity envieth not; charity vaunteth not itself, is not puffed up.",
    "And now, Lord, what wait I for? my hope is in thee.",
    "Where no counsel is, the people fall: but in the multitude of counsellors there is safety.",
    "And the work of righteousness shall be peace; and the effect of righteousness quietness and assurance for ever.",
    "Be strong, and of good courage, and do it: fear not, nor be dismayed.",
    "Who is a God like unto thee, that pardoneth iniquity.",
    "It is good that a man should both hope and quietly wait for the salvation of the LORD.",
    "For our heart shall rejoice in him, because we have trusted in his holy name.",
    "And I say also unto thee, That thou art Peter, and upon this rock I will build my church; and the gates of hell shall not prevail against it.",
    "And these signs shall follow them that believe; In my name shall they cast out devils; they shall speak with new tongues;",
    "No man hath seen God at any time. If we love one another, God dwelleth in us.",
    "Happy is he that hath the God of Jacob for his help, whose hope is in the LORD his God.",
    "I will instruct thee and teach thee in the way which thou shalt go.",
    "The LORD lift up his countenance upon thee, and give thee peace.",
    "Though an host should encamp against me, my heart shall not fear.",
    "I, even I, am he that blotteth out thy transgressions for mine own sake.",
    "Rest in the LORD, and wait patiently for him.",
    "The LORD hath done great things for us; whereof we are glad.",
    "But ye shall receive power, after that the Holy Ghost is come upon you: and ye shall be witnesses unto me both in Jerusalem, and in all Judæa, and in Samaria, and unto the uttermost part of the earth.",

]   
let verse = ["Gen 1:1", "John 11:35", "Isa 60:1", "Joel 2:28", "Matt 11:28", "John 1:1", "2Tim 2:15",
    "Matt 28:19", "Haggi 1:6", "Hebrews 11:1", "Philippians 4:13", "1 Corinthians 13:4", "Romans 15:13",
    "Proverbs 3:5-6", "John 14:27", "Joshua 1:9", "Ephesians 4:32", "James 1:4", "Nehemiah 8:10", 
    "Matthew 17:20", "Isaiah 40:31", "1 John 4:8", "Jeremiah 29:11", "Psalm 32:8", "Colossians 3:15",
    "2 Timothy 1:7", "Matthew 6:14", "Romans 12:12", "Psalm 16:11", "Romans 10:17", "Psalm 46:1",
    "John 15:12", "Psalm 39:7", "Psalm 119:105", "Isaiah 26:3",  "Deuteronomy 31:6",  "Luke 6:37",
    "Ecclesiastes 7:8", "Romans 12:12", "2 Corinthians 5:7", "Psalm 28:7", "Romans 13:10", "Psalm 33:18",
    "Isaiah 58:11", "John 16:33", "1 Chronicles 28:20", "Psalm 103:12",  "Galatians 6:9",  "Psalm 118:24", 
    "James 1:6", "Isaiah 41:10", "1 John 4:16", "Psalm 31:24", "Proverbs 16:9", "Philippians 4:7", "Psalm 27:1", 
    "Micah 7:18", "Lamentations 3:25-26", "Psalm 94:19", "Romans 1:17", "Nehemiah 8:10", "1 Peter 4:8", 
    "Romans 15:4", "Psalm 37:23", "Isaiah 54:10", "Psalm 31:24", "Colossians 3:13", "James 5:7", "Psalm 16:11",
    "Mark 11:22", "2 Chronicles 15:7", "John 13:34", "Psalm 71:5", "Isaiah 30:21",  "Romans 5:1", "1 Corinthians 16:13",
    "Luke 17:3-4", "Psalm 30:5", "Hebrews 12:2", "Psalm 18:32", "1 John 3:18", "Lamentations 3:24", "Psalm 25:4-5",
    "John 14:27", "Deuteronomy 31:8", "Matthew 18:21-22", "Ecclesiastes 7:8", "1 Corinthians 2:5", "Exodus 15:2",
    "1 John 4:19", "Romans 5:5", "Isaiah 48:17", "Psalm 29:11", "2 Samuel 22:33", "Psalm 86:5", "Psalm 37:7",
    "Isaiah 61:10", "Galatians 2:20", "Nehemiah 4:14", "Romans 12:10", "Psalm 130:5", "Proverbs 11:14", "Isaiah 32:17",
    "1 Chronicles 28:20",  "Micah 7:19", "John 3:16",  "Psalm 19:8", "Matthew 21:22", "Isaiah 12:2", "Ephesians 5:2", 
    "Psalm 42:5", "Psalm 48:14", "John 16:33", "Heb 12:14", "Psalm 103:12", "James 5:8", "Psalm 118:24", "2 Timothy 4:7",
    "Psalm 23:4", "Colossians 3:14", "Matt 7:7", "Joel 2:28", "Isaiah 26:3", "Joshua 1:6", "Matthew 18:21-22", "Romans 8:25",
    "Psalm 16:11", "1 Peter 1:8-9", "Isaiah 41:10", "John 13:35", "Psalm 71:14", "Psalm 32:8", "Romans 5:1", "1 Chronicles 28:20",
    "Ephesians 4:32", "Psalm 37:34", "Psalm 126:2", "Romans 10:17", "Psalm 46:1", "1 John 3:16", "Lamentations 3:21-23", "Psalm 23:3",
    "Isaiah 9:6", "Psalm 27:1", "Psalm 32:1-2", "James 5:11", "Psalm 28:7", "Hebrews 11:6", "Isaiah 40:29", "Romans 5:8", "Psalm 71:5",
    "Proverbs 4:20", "John 14:1", "Amos 3:3", "Isaiah 1:18","Romans 8:6", "Psalm 33:21", "Romans 12:2", "Psalm 18:32", "1 Peter 4:8",
    "Romans 15:13", "Proverbs 22:6", "Colossians 3:15", "Joshua 1:9", "Luke 6:37", "Ecclesiastes 7:8", "Psalm 30:5", "John 10:10",
    "Psalm 28:7", "John 15:12", "Psalm 39:7", "Psalm 32:8", "Job 14:1", "Ephesians 6:1", "Ephesians 4:32", "Galatians 6:9", "Psalm 118:24",
    "James 1:6", "Galatians 6:17", "1 John 4:16", "Psalm 31:24", "Romans 9:16", "Psalm 107:1", "Psalm 27:1", "Micah 7:18", "Lamentations 3:25-26",
    "Psalm 94:19", "Mark 11:22", "Micah 7:8", "Matthew 28:19", "Psalm 130:5", "Isaiah 30:21", "1John 5:4", "1Corithians 2:9", "Psalm 103:12", 
    "Hebrews 10:36", "Romans 14:17", "Luke 18:27", "Psalm 84:5", "Ephesians 5:2", "Hebrews 6:19", "Phillipians 2:5", "Isaiah 26:12", "1 Corinthians 16:13",
    "Daniel 9:9", "Psalm 40:1", "John 16:22", "Psalm 56:3", "Isaiah 12:2", "2 Thessalonians 3:5", "Psalm 146:5", "Job 23:10", "2 Thessalonians 3:16",
    "Psalm 112:7", "Isaiah 43:25", "Psalm 27:14", "Psalm 16:11", "John 6:29", "Psalm 138:3", "1 John 4:19", "Psalm 62:5", "Isaiah 58:11", "Psalm 85:8",
    "Acts 18:9", "Psalm 86:5", "Psalm 103:2", "Psalm 43:4", "Habakkuk 2:4", "Psalm 29:11", "John 13:35", "Psalm 119:114", "Proverbs 20:24", "Isaiah 32:17",
    "Psalm 56:11", "Psalm 130:4", "James 1:4", "Nehemiah 12:43", "John 1:5", "Ephesians 6:2", "Romans 13:10", "Psalm 33:18",  "Isaiah 42:16", "Leviticus 26:6",
    "Psalm 118:6", "Psalm 25:18", "Psalm 62:1", "Psalm 5:11", "John 11:40", "Isaiah 52:1", "1 Corinthians 13:13", "Psalm 119:49", "Psalm 143:10", "Isaiah 57:19", 
    "Psalm 91:5", "2 Chronicles 7:14", "Psalm 37:7", "Isaiah 61:10", "Hebrews 10:23", "Psalm 46:5", "John 14:23", "Psalm 71:14", "Exodus 15:13", "Psalm 119:165",
    "Psalm 23:4", "Isaiah 44:22", "Psalm 123:2", "Psalm 126:3", "Luke 1:37", "Psalm 73:26", "1 John 4:7", "Psalm 147:11", "Psalm 25:9", "Isaiah 48:18", "Psalm 138:7",
    "Psalm 51:1", "Proverbs 14:29", "Psalm 95:1", "John 8:24","Isaiah 33:2", "Ephesians 3:17", "Psalm 119:81", "Psalm 37:23", "Job 22:21", "Psalm 27:3", "Isaiah 55:7",
    "Psalm 145:15", "Psalm 21:6", "Psalm 9:10", "Isaiah 35:4", "Proverbs 10:12", "Psalm 42:11", "Psalm 16:7", "Numbers 6:26", "Psalm 112:8", "Jeremiah 33:8", "Psalm 131:2",
    "Psalm 66:1", "Matthew 9:22", "Psalm 89:13", "Song of Solomon 8:7", "Psalm 119:116", "Psalm 73:24", "Isaiah 54:10", "Micah 7:19", "Psalm 75:2", "Psalm 32:11", "John 20:29",
    "Psalm 18:39", "Romans 12:10", "Psalm 119:166", "Isaiah 45:2", "Psalm 4:8", "Psalm 46:2", "Jeremiah 31:34", "Psalm 92:13", "Psalm 97:11", "Luke 17:6", "Psalm 61:2", "Proverbs 3:12",
    "Psalm 119:90", "Psalm 119:133", "Isaiah 26:3", "Psalm 91:2", "Daniel 9:18", "Psalm 130:6", "Psalm 149:4", "Matthew 8:26", "Psalm 28:8", "1 John 3:18", "Psalm 62:8", "Isaiah 49:16",
    "Psalm 34:14", "Psalm 91:11", "Isaiah 38:17", "Psalm 37:34", "Psalm 98:4", "Hebrews 4:16", "Psalm 46:10", "Matthew 6:33", "1Peter 5:10", "Psalm 37:5", "Romans 13:8", "Revelation 4:8",
    "Psalm 103:12", "Romans 8:25", "James 1:22", "Matthew 21:21", "2Timothy 3:1", "1 Corinthians 13:4", "Psalm 39:7", "Proverbs 11:14", "Isaiah 32:17", "1 Chronicles 28:20", "Micah 7:18",
    "Lamentations 3:26", "Psalm 33:21", "Matthew 16:18", "Mark 16:17", "1 John 4:12", "Psalm 146:5", "Psalm 32:8", "Numbers 6:26",
]
let introduction = "Verse of the day";
let startDate = new Date(2026, 0, 23);
let today = new Date();

function daysSinceStart(start, today) {
    const diff = today - start; // difference in milliseconds
    return Math.floor(diff / (1000 * 60 * 60 * 24)); // convert to full days
}

let index = daysSinceStart(startDate, today) % scripture.length;

result.textContent = introduction;
output.textContent = scripture[index];
display.textContent = verse[index];

let day = new Date()
let dayName = day.getHours();

if (dayName < 12) {
    document.getElementById("displayHours").innerHTML =  '<i class="fa-solid fa-sun" style="color: orange;"></i> Good Morning';
} else if(dayName < 18){
    document.getElementById("displayHours").textContent = `<i class="fa-solid fa-sun" style="color: orange;"></i> Good Afternoon`;
} else{
   document.getElementById("displayHours").textContent = `<i class="fa-solid fa-moon"></i> Good Evening`; 
}

const backgrounds = [
    "garden.png",
    "bg-img1.png",
    "bg-img2.png",
    "bg-img3.png",
    "bg-img4.png",
    "bg-img5.png",
    "bg-img6.png",
    "bg-img7.png",
];

const el = document.getElementById("card");

// Day of year (1–366)
const start = new Date(new Date().getFullYear(), 0, 0);
const newDay = new Date();
const dayOfYear = Math.floor((newDay - start) / 86400000);

// Pick image based on day (loops automatically)
const timing = dayOfYear % backgrounds.length;

el.style.backgroundImage = `
  linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.6)),
  url(${backgrounds[timing]})
`;

const toTop = document.querySelector(".to-top")

window.addEventListener("scroll", function(){
    if (this.window.pageYOffset > 100) {
        toTop.classList.add("active");
    } else{
        toTop.classList.remove("active");
    }
})

const observer = new IntersectionObserver((entries, observer) => {
  entries.forEach(entry => {
    if (entry.isIntersecting) {
      entry.target.classList.add("active");
      observer.unobserve(entry.target); // Play once
    }
  });
}, { threshold: 0.25 }); // Trigger when 25% visible

document.querySelectorAll(".reveal").forEach(el => {
  observer.observe(el);
});

function updateClock(){
    const time = new Date();
    const hours = time.getHours().toString().padStart(2, 0);
    const meridiem = hours >= 12 ? "PM" : "AM";
    const minutes = time.getMinutes().toString().padStart(2, 0);
    const seconds = time.getSeconds().toString().padStart(2, 0);
    const timeStrings = `${hours}: ${minutes}: ${seconds}: ${meridiem}`;
    document.getElementById("clock").textContent = timeStrings;
}

updateClock();
setInterval(updateClock, 1000);


















